/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as ConsultIndexRouteImport } from './routes/consult/index'
import { Route as ConsultChatRouteImport } from './routes/consult/chat'
import { Route as ConsultIntentRouteImport } from './routes/consult/intent'
import { Route as FormIndexRouteImport } from './routes/form/index'
import { Route as ResultRunIdRouteImport } from './routes/result/$runId'
import { Route as UpgradeIndexRouteImport } from './routes/upgrade/index'
import { Route as ApiConsultChatRouteImport } from './routes/api/consult/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultIndexRoute = ConsultIndexRouteImport.update({
  id: '/consult/',
  path: '/consult/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultChatRoute = ConsultChatRouteImport.update({
  id: '/consult/chat',
  path: '/consult/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultIntentRoute = ConsultIntentRouteImport.update({
  id: '/consult/intent',
  path: '/consult/intent',
  getParentRoute: () => rootRouteImport,
} as any)
const FormIndexRoute = FormIndexRouteImport.update({
  id: '/form/',
  path: '/form/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRunIdRoute = ResultRunIdRouteImport.update({
  id: '/result/$runId',
  path: '/result/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeIndexRoute = UpgradeIndexRouteImport.update({
  id: '/upgrade/',
  path: '/upgrade/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsultChatRoute = ApiConsultChatRouteImport.update({
  id: '/api/consult/chat',
  path: '/api/consult/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consult/chat': typeof ConsultChatRoute
  '/consult/intent': typeof ConsultIntentRoute
  '/result/$runId': typeof ResultRunIdRoute
  '/compare/': typeof CompareIndexRoute
  '/consult/': typeof ConsultIndexRoute
  '/form/': typeof FormIndexRoute
  '/upgrade/': typeof UpgradeIndexRoute
  '/api/consult/chat': typeof ApiConsultChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consult/chat': typeof ConsultChatRoute
  '/consult/intent': typeof ConsultIntentRoute
  '/result/$runId': typeof ResultRunIdRoute
  '/compare': typeof CompareIndexRoute
  '/consult': typeof ConsultIndexRoute
  '/form': typeof FormIndexRoute
  '/upgrade': typeof UpgradeIndexRoute
  '/api/consult/chat': typeof ApiConsultChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consult/chat': typeof ConsultChatRoute
  '/consult/intent': typeof ConsultIntentRoute
  '/result/$runId': typeof ResultRunIdRoute
  '/compare/': typeof CompareIndexRoute
  '/consult/': typeof ConsultIndexRoute
  '/form/': typeof FormIndexRoute
  '/upgrade/': typeof UpgradeIndexRoute
  '/api/consult/chat': typeof ApiConsultChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consult/chat'
    | '/consult/intent'
    | '/result/$runId'
    | '/compare/'
    | '/consult/'
    | '/form/'
    | '/upgrade/'
    | '/api/consult/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consult/chat'
    | '/consult/intent'
    | '/result/$runId'
    | '/compare'
    | '/consult'
    | '/form'
    | '/upgrade'
    | '/api/consult/chat'
  id:
    | '__root__'
    | '/'
    | '/consult/chat'
    | '/consult/intent'
    | '/result/$runId'
    | '/compare/'
    | '/consult/'
    | '/form/'
    | '/upgrade/'
    | '/api/consult/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultChatRoute: typeof ConsultChatRoute
  ConsultIntentRoute: typeof ConsultIntentRoute
  ResultRunIdRoute: typeof ResultRunIdRoute
  CompareIndexRoute: typeof CompareIndexRoute
  ConsultIndexRoute: typeof ConsultIndexRoute
  FormIndexRoute: typeof FormIndexRoute
  UpgradeIndexRoute: typeof UpgradeIndexRoute
  ApiConsultChatRoute: typeof ApiConsultChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult/': {
      id: '/consult/'
      path: '/consult'
      fullPath: '/consult/'
      preLoaderRoute: typeof ConsultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult/chat': {
      id: '/consult/chat'
      path: '/consult/chat'
      fullPath: '/consult/chat'
      preLoaderRoute: typeof ConsultChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult/intent': {
      id: '/consult/intent'
      path: '/consult/intent'
      fullPath: '/consult/intent'
      preLoaderRoute: typeof ConsultIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/': {
      id: '/form/'
      path: '/form'
      fullPath: '/form/'
      preLoaderRoute: typeof FormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$runId': {
      id: '/result/$runId'
      path: '/result/$runId'
      fullPath: '/result/$runId'
      preLoaderRoute: typeof ResultRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade/': {
      id: '/upgrade/'
      path: '/upgrade'
      fullPath: '/upgrade/'
      preLoaderRoute: typeof UpgradeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consult/chat': {
      id: '/api/consult/chat'
      path: '/api/consult/chat'
      fullPath: '/api/consult/chat'
      preLoaderRoute: typeof ApiConsultChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultChatRoute: ConsultChatRoute,
  ConsultIntentRoute: ConsultIntentRoute,
  ResultRunIdRoute: ResultRunIdRoute,
  CompareIndexRoute: CompareIndexRoute,
  ConsultIndexRoute: ConsultIndexRoute,
  FormIndexRoute: FormIndexRoute,
  UpgradeIndexRoute: UpgradeIndexRoute,
  ApiConsultChatRoute: ApiConsultChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
